# Generated by Django 2.2.13 on 2021-03-19 12:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import fin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=30, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='datasource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourcename', models.CharField(max_length=200, verbose_name='Source Name')),
            ],
        ),
        migrations.CreateModel(
            name='incomesource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourcename', models.CharField(max_length=30, verbose_name='Income Source')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=200, verbose_name='Project')),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(max_length=200, verbose_name='Note')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_projects', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
        ),
        migrations.CreateModel(
            name='search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchname', models.CharField(max_length=200, verbose_name='Search')),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(default=' ', max_length=20, verbose_name='Note')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_searches', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_searches', to='fin.project', verbose_name='Search')),
            ],
        ),
        migrations.CreateModel(
            name='sentmentlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myword', models.CharField(max_length=200, unique=True, verbose_name='Word')),
                ('imporession', models.CharField(max_length=200, verbose_name='Impression')),
            ],
        ),
        migrations.CreateModel(
            name='textstream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200, verbose_name='Source')),
                ('mytext', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('impression', models.CharField(default='Neutral', max_length=2000, verbose_name='Impression')),
                ('emotion', models.CharField(default='No thing', max_length=200, verbose_name='Emotion')),
                ('score', models.IntegerField(default=0)),
                ('mylength', models.IntegerField(blank=True, null=True)),
                ('frequency', models.IntegerField(blank=True, null=True)),
                ('lang', models.CharField(default='No thing', max_length=20, verbose_name='Language')),
                ('location', models.CharField(default='No thing', max_length=20, verbose_name='Location')),
                ('note', models.CharField(default='', max_length=20, verbose_name='Note')),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('textdomain', models.CharField(default='No thing', max_length=200, verbose_name='Domain')),
                ('keyword1', models.CharField(blank=True, max_length=200, null=True, verbose_name='keyword1')),
                ('keyword2', models.CharField(blank=True, max_length=200, null=True, verbose_name='keyword2')),
                ('maxitems', models.IntegerField(default=10)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_textstream', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('search', models.ForeignKey(default=fin.models.defaultsearch, on_delete=django.db.models.deletion.CASCADE, related_name='search_texts', to='fin.search', verbose_name='Search')),
            ],
        ),
        migrations.CreateModel(
            name='searchdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword1', models.CharField(blank=True, max_length=200, null=True, verbose_name='keyword1')),
                ('keyword2', models.CharField(blank=True, max_length=200, null=True, verbose_name='keyword2')),
                ('maxitems', models.IntegerField(default=10)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_searchdetails', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('search', models.ForeignKey(default=fin.models.defaultsearch, on_delete=django.db.models.deletion.CASCADE, related_name='search_searchdetails', to='fin.search', verbose_name='Search')),
            ],
        ),
        migrations.CreateModel(
            name='projectarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=200, verbose_name='Project Name')),
                ('datasource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_project', to='fin.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=30, verbose_name='Item Name')),
                ('category', models.ForeignKey(default=fin.models.defaultcategory, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_factory', to='fin.category')),
            ],
        ),
        migrations.CreateModel(
            name='finbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000, verbose_name='Discreption')),
                ('clarification', models.CharField(default='No thing', max_length=2000, verbose_name='Clarification')),
                ('transactionc', models.CharField(default='No thing', max_length=20, verbose_name='Transaction Category')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('updatedate', models.DateTimeField(auto_now=True)),
                ('transactiondate', models.DateField(default=datetime.datetime(2021, 3, 19, 12, 25, 38, 523177, tzinfo=utc), verbose_name='Transaction Date')),
                ('incomesource', models.CharField(default='No thing', max_length=20)),
                ('department', models.CharField(default='No thing', max_length=20)),
                ('subdepartment', models.CharField(default='No thing', max_length=20)),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Note')),
                ('fyear', models.IntegerField(default=0)),
                ('fmonth', models.IntegerField(default=0)),
                ('fday', models.IntegerField(default=0)),
                ('category', models.ForeignKey(default=fin.models.defaultcategory, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_fin', to='fin.category')),
            ],
        ),
    ]
